name: "Cystatic PR Analyzer"
description: "Sends PR code changes to Cystatic API for analysis"

inputs:
  github_token:
    description: "GitHub token for posting comments"
    required: true

  cystatic_api_key:
    description: "API key to authenticate with Cystatic API"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
    INPUT_CYSTATIC_API_KEY: ${{ inputs.cystatic_api_key }}